import { describe, expect, it } from 'vitest';
import {
  generateArabicHarakat,
  generateLatin,
  looksFullyDiacritized
} from '../../src/core/transliteration/index.js';

describe('generateLatin (Arabic -> Brill)', () => {
  it('converts simple consonant + short vowel clusters', () => {
    expect(generateLatin('كَتَبَ')).toBe('kataba');
    expect(generateLatin('كُتُبْ')).toBe('kutub');
  });

  it('converts long vowels via mater lectionis', () => {
    expect(generateLatin('كَاتِبْ')).toBe('kātib');
    expect(generateLatin('نُورْ')).toBe('nūr');
  });

  it('converts shadda as consonant gemination', () => {
    expect(generateLatin('مُحَمَّدْ')).toBe('muḥammad');
  });

  it('converts the definite article', () => {
    expect(generateLatin('الْقَاهِرَة')).toBe('al-qāhira');
  });

  it('converts hamza seats to ʾ', () => {
    expect(generateLatin('سَأَلَ')).toBe('saʾala');
  });

  it('converts the definite article before a sun letter without doubling the consonant', () => {
    // Regression test: the sun-letter shadda used to be misread as true
    // gemination, producing a doubled consonant ("al-zzahrāwī") instead of
    // the correct unassimilated Brill spelling ("al-zahrāwī").
    expect(generateLatin('الرَّحْمَان')).toBe('al-raḥmān');
    expect(generateLatin('التِّرْمِذِي')).toBe('al-tirmidhī');
    expect(generateLatin('الزَّهْرَاوِي')).toBe('al-zahrāwī');
  });

  it('still doubles a genuinely geminated root consonant (true shadda, not article assimilation)', () => {
    expect(generateLatin('مُحَمَّدْ')).toBe('muḥammad');
  });

  it('round-trips a realistic multi-word name exactly as generated by the forward engine', () => {
    const forward = generateArabicHarakat('Abū al-Qāsim Khalaf al-Zahrāwī');
    expect(looksFullyDiacritized(forward)).toBe(true);
    expect(generateLatin(forward)).toBe('ʾabū al-qāsim khalaf al-zahrāwī');
  });

  it('round-trips through the forward engine for regular (non-idiomatic) names', () => {
    const roundTrip = (latin: string): string => generateLatin(generateArabicHarakat(latin));
    expect(roundTrip('Karīm')).toBe('karīm');
    expect(roundTrip('Sāmir')).toBe('sāmir');
    expect(roundTrip('Nūr')).toBe('nūr');
    expect(roundTrip('Yūsuf')).toBe('yūsuf');
    expect(roundTrip('Zaynab')).toBe('zaynab');
    expect(roundTrip('Ḥasan')).toBe('ḥasan');
  });
});

describe('looksFullyDiacritized', () => {
  it('accepts text where every consonant carries a harakat mark', () => {
    expect(looksFullyDiacritized('مُحَمَّدْ')).toBe(true);
  });

  it('accepts a word-final bare consonant (pausal form) — matching the forward engine\u2019s own convention', () => {
    // The forward engine leaves the very final consonant of a word
    // unmarked (e.g. "Bakr" -> بَكْر, "Khalaf" -> خَلَف) — requiring a mark
    // there too would reject the engine's own real output.
    expect(looksFullyDiacritized('بَكْر')).toBe(true);
    expect(looksFullyDiacritized('خَلَف')).toBe(true);
  });

  it('still rejects a bare consonant that is NOT word-final (genuinely missing an internal vowel)', () => {
    expect(looksFullyDiacritized('بَكرْ')).toBe(false); // internal ك has no mark
  });

  it('accepts the definite article\u2019s lām before both sun and moon letters, unmarked, mid-phrase', () => {
    const phrase = generateArabicHarakat('Abū al-Qāsim Khalaf al-Zahrāwī');
    expect(looksFullyDiacritized(phrase)).toBe(true);
  });

  it('accepts mater-lectionis و/ي mid-word (no mark of their own — the vowel sits on the preceding consonant)', () => {
    // "Khaldūn" -> خَلْدُون: the و (long ū) sits between د and ن with no
    // mark of its own — only the preceding د carries the damma.
    const phrase = generateArabicHarakat('Ibn Khaldūn');
    expect(looksFullyDiacritized(phrase)).toBe(true);
  });

  it('rejects undotted Arabic text', () => {
    expect(looksFullyDiacritized('محمد')).toBe(false);
  });

  it('rejects partially diacritised text', () => {
    expect(looksFullyDiacritized('مُحمد')).toBe(false);
  });
});
